# Generated by Django 2.0.13 on 2019-07-13 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=400)),
                ('time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='search.Book')),
                ('kb', models.URLField(unique=True)),
                ('yp', models.URLField(unique=True)),
                ('bd', models.URLField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='auth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Author'),
        ),
        migrations.AddField(
            model_name='book',
            name='pub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Publisher'),
        ),
    ]
