# Generated by Django 2.0.13 on 2019-08-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=50)),
                ('road_address_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('in_seoul', models.BooleanField()),
                ('x', models.CharField(max_length=20)),
                ('y', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='auth',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pub',
        ),
        migrations.RemoveField(
            model_name='url',
            name='book',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.DeleteModel(
            name='Url',
        ),
    ]
